language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2
env:
  - APN_MULTIPLE_APPS=false
  - APN_MULTIPLE_APPS=true
script: rspec spec
gemfile:
  - Gemfile
  - Gemfile.sidekiq
  - Gemfile.resque